name: Hexo Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Clean
      uses: heisenbergye/heisenbergye.github.io@master
      with:
        args: clean
    - name: Generate
      uses: heisenbergye/heisenbergye.github.io@master
      with:
        args: generate
    - name: Deploy
      uses: heisenbergye/heisenbergye.github.io@master
      env:
        EMAIL: heisenbergye@outlook.com
        NAME: ye
      with:
        args: deploy
